### PR TITLE
Updating svc with new Auth0 V2 API

### PR DESCRIPTION
**Pull request by kevincol54**
- Moving to the new Auth0 V2 API.
  - New calls to UPDATE and GET user
- Switched to AVA test framework
  - Spread across several files for test isolation and to allow concurrent tests across multiple processes
- Updated package.json
  - Set engines, keywords, authors

### CODE REVIEW

**Comment by twilson63** [comment]
Looks like some problems with ci could you remove .10 and .8 from the Travis.yml and indicate 4, 5, and 6 of nose is supported?

**Comment by twilson63** [comment]
Looks good otherwise!!!

**Comment by twilson63** [comment]
Another question, why are you setting the response success object with a message wrapper?

Why not just return the result object?

**Comment by kevincol54** [comment]
I do not see any reason to not just return the result object. My only thought was, that by doing it this way, it emulates the way the old service returned things, so it might make it easier for others to update to the newest version since there would be less code changes because of the fewer changes to the services I/O.

**Comment by twilson63** [comment]
Got it, I wonder why I did it that way, anyway, I removed the message attribute, just to return the object, we can change it back if you want, or if someone else would like to, it is a breaking change because it requires nodejs 6, I should update the major version for a breaking change

**Comment by twilson63** [comment]
Could not stop refactoring, it may be over done, so feel free to back it out, if you are not able to follow the code, or see bugs or problems.

**Comment by kevincol54** [comment]
Refactor looks good! I like the inclusion of event streams. Do we want to test the logic where we default to a `NULL` value if the object property is not present? Maybe test that the catch picks up the correct error when null is passed into the Auth0 API call? This may be getting too granular and may result in the tests actually testing other libraries code, but a thought.

**Comment by twilson63** [comment]
Hey Kevin,

I went back and forth on that, the path command will return null and then
the api call should error out, so the error should be handled with the
refactor, you may want to test that scenario. But I think by defaulting to
null if no path will take care of the UserId and UserData validation check.

Thanks

Tom

On Fri, Apr 29, 2016 at 9:34 AM, Kevin Collins notifications@github.com
wrote:

> Refactor looks good! I like the inclusion of event streams. Do we want to
> test the logic where we default to a NULL value if the object property is
> not present? Maybe test that the catch picks up the correct error when null
> is passed into the Auth0 API call? This may be getting too granular and may
> result in the tests actually testing other libraries code, but a thought.
> 
> —
> You are receiving this because you commented.
> Reply to this email directly or view it on GitHub
> https://github.com/twilson63/palmettoflow-auth0-svc/pull/1#issuecomment-215712656

## 

Tom Wilson
Jack Russell Software, A Tabula Rasa Healthcare Division
494 Wando Park Blvd
Mount Pleasant, SC  29464
Phone: 843-606-6484
Mobile: 843-469-5856
Email: tom@jackhq.com
Web: http://www.jackhq.com
Calendar:
http://www.google.com/calendar/embed?src=tom%40jackrussellsoftware.com&ctz=America/New_York
http://www.jackhq.com/calendar

This e-mail may contain information that is confidential, privileged or
otherwise protected from disclosure by the Health Insurance Portability and
Accountability Act (HIPAA) and other state and federal laws.  This
information is intended only for the individual names above.  Any review,
use disclosure or dissemination of this material is strictly prohibited.
If you receive this information in error, please notify CareKinesis
immediately at 888-974-2763 and delete the original at once.

**Comment by twilson63** [comment]
Is this good to merge?

**Comment by kevincol54** [comment]
I believe it is. As long as You are comfortable with the error handling I put in place yesterday, I think we can go ahead and merge it on in.

**Pull request merged**
